### PR TITLE
Support `--service` cmd line arg for headless detection

### LINKED ISSUE #1542: ASF-ui should be aware of --service in regards to bot input dialogue
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

ASF-ui currently does not display a dialogue box if user is using `--service` cmd-line arg, but doesn't specify `Headless: true` in his global ASF config. This is suboptimal, as `--service` implicitly defines `Headless: true`, and therefore ASF-ui can use input methods in this scenario.

### Solution

Add a very simple enhancement of `bool supportsInputDialogue = Service || GlobalConfig.Headless` in place of current `bool supportsInputDialogue = GlobalConfig.Headless`.

### Why currently available solutions are not sufficient?

If user uses `--service` but doesn't specify `Headless: true` in his config, ASF-ui will not display a dialogue box for input, as it's not aware that `--service` implicitly specified `Headless`. ASF should not report `Headless: true` on its own, as that doesn't come from the config.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

https://github.com/JustArchiNET/ArchiSteamFarm/commit/78a88979dc85a633d3c5bfd5eda1301f252006a3

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Closes #1542 

@JustArchi, please feel free to give this a quick test.

### CODE REVIEW

**Review by JustArchi — APPROVED** [review]
LGTM, @Abrynos can you test?

**Comment by Abrynos** [comment]
> LGTM, @Abrynos can you test?

I'd rather work on my thesis right now.

**Comment by JustArchi** [comment]
> > LGTM, @Abrynos can you test?
> 
> I'd rather work on my thesis right now.

It's OK, @legendofmiracles is on that :grin:

**Review by legendofmiracles — APPROVED** [review]
Works here

**Pull request merged**
