### PR TITLE
[WIP] Add CONTRIBUITING.md

### PR DESCRIPTION
**Pull request by MrBurrBurr**

### CODE REVIEW

**Comment by JustArchi** [comment]
I like how instead of putting that stuff in **[editorconfig](https://github.com/JustArchiNET/ASF-ui/blob/master/.editorconfig)** and making it possible for all IDEs to pick it up automatically, you decide to go with a style guideline document that people are expected to read and memorize 🤔

**Comment by MrBurrBurr** [comment]
I wasn't aware that `editorconfig` could handle all the rules we decided upon. I will look it up and change that file instead of writing a complicated guide.

**Comment by JustArchi** [comment]
Even if it can't handle everything, it can definitely handle **majority** of stuff that you put so far. Right now I see that editorconfig is empty and there are some coding guidelines up, so I feel like C developer back in 1995 🤔.

**Comment by JustArchi** [comment]
You can take a look at **[mine](https://github.com/JustArchiNET/ArchiSteamFarm/blob/master/.editorconfig)** and start from the top which should be sensible enough, then look up what editorconfig supports for js, vue and all other stuff and use what you consider good enough.

In my C# case, editorconfig supports everything that is important.

**Comment by Aareksio** [comment]
I think we're following airbnb styleguide (one of the most well-known). We can add eslint config and enable the preset.

**Pull request closed without merging**
