### PR TITLE
Redirect user to setup page upon receiving 504 error code

### LINKED ISSUE #1039: Inform user about 504 gateway timeout
I imagine some kind of overlay saying something like "Lost connection to ASF. Trying to reconnect..."

### LINKED ISSUE #1142: Reload ASF-ui page after ASF update
## Description
After successful ASF update ASF-ui page in browser does not auto reload. Probably hard reload is needed (CTRL+F5).

## Steps to reproduce
1. Open ASF-ui page in browser,
2. Make sure there is ASF update available,
3. Update ASF either way (interactive console, chat, ASF-ui),
4. ASF updated and restarted itself as well as started new IPC server (see on attached screenshot local version is 4.3.1.1), but ASF-ui page was not reloaded (see bottom right corner on attached screenshot).

## Purpose

Reload ASF-ui page in browser to update web interface after successful ASF update and subsequent ASF restart, which implies that IPC server was also restarted.

## Screenshots
chrome_9hwWoPaNb8

### LINKED ISSUE #1157: Rate Limited when Changing ASF IPC password
## Description
When changing a password in ASF UI for the IPC login, you become rate limited

## Steps to reproduce

1. Go to 'Global Configuration'
2. Change password
3. Reload the page
4. You are rate limited

## Expected behavior
ASF UI should stop sending AJAX requests to the server and then reload the webpage showing a login screen.

## Current behavior
ASF UI keeps sending AJAX requests to the server in order to receive log data, status data, but since the password has changed, we are no longer logged in. On page reload, we get rate limited because the website kept on sending requests every second or so.

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Closes #1039
Fixes #1157

### CODE REVIEW

**Comment by Botan626** [comment]
1. Does not notify about new version completely.
image

2. After I closed ASF window while keeping ASF-ui page opened, it did show Network Error notification. But I don't see any 'setup page'.
image

3. I did update ASF to v4.3.1.2 via interactive console, and ASF-ui did update itself somehow, but the new version was 'ASF 4.3.1.2 - win-x64 - cc82a79', when I pressed CTRL+F5, it changed its version to 'ASF 4.3.1.2 - win-x64 - 3f03638'.
image

4. I didn't perform any checks re issue #1157.

**Comment by Botan626** [comment]
I also updated via Update button in ASF-ui, Log page wasn't reloaded, though I had Error and Warning in ASF while updating, but ASF finished the update process.

ASF log: https://pastebin.com/raw/tHnz4uic
image
image

**Comment by Botan626** [comment]
This is what ASF-ui told me when I updated by executing update command.
image
Plus there is 1 warning in ASF [log](https://pastebin.com/raw/4QbRib97).

There are no errors and warnings if I update via interactive console, I checked several times.

**Comment by MrBurrBurr** [comment]
Funny, it works in development mode... I will check later today, thank you for your feedback.

**Comment by MrBurrBurr** [comment]
Thank you @Botan626 for your feedback.

All of the issues you mentioned should be fixed in PR #1331.

**Comment by Botan626** [comment]
It always opens Bot page after reconnecting, though the default page is different, maybe it should open the last page it was on after connection was lost, and default page after restart or update.

There is no notification about new ASF release after reconnecting, but there is exclamation mark.

It's not possible to change the language on Setup page, maybe this panel should to be removed.

After successful update it still shows exclamation mark for a new release available and incorrect ASF-ui vesion, probably needs a hard page reload.
incorrect:
image
correct:
image

**Comment by Botan626** [comment]
I think adding a countdown for seconds would be nice.
image

**Comment by MrBurrBurr** [comment]
> It always opens Bot page after reconnecting, though the default page is different, maybe it should open the last page it was on after connection was lost, and default page after restart or update.

I will take a look at this.

> It's not possible to change the language on Setup page, maybe this panel should to be removed.

This should be possible. But I might have an idea what broke it. I will fix it.

> There is no notification about new ASF release after reconnecting, but there is exclamation mark.

This is as it should be since the notification will only be shown upon initial page load or refresh. Otherwise it would be too intrusive.

> After successful update it still shows exclamation mark for a new release available and incorrect ASF-ui vesion, probably needs a hard page reload.

This should be fixed with my future PR regarding #1330.

> I think adding a countdown for seconds would be nice.

Yep, that's something I was thinking about too.

**Pull request merged**
