### PR TITLE
ASF now uses string to represent its version

### LINKED ISSUE #761: UI shows undefined version of ASF
Hi, what's up?

I updated ASF to v4.1.0.1, pre-release verison.
image

But UI can not define ASF version, please take a close look:

image

### PR DESCRIPTION
**Pull request by guixxx**
## Description
Starting from version 4.1.0.1, ASF's API will use a string to represent its version, instead of an object like it used to be. Source: https://github.com/JustArchiNET/ArchiSteamFarm/commit/a49c72426cbc709190d740c96e5f538d80b031f6

## Screenshots
Before:
image
After:
image

## Additional information
Before you accept this PR, I have two important questions:
1. This fix obviously will not work in older versions of ASF (4.1.0.0 and older). Now, I could re-write this fix so it can work in all versions, but in order to do that, I need to know if backwards compatibility within ASF-ui is important to you guys.
2. I haven't removed the [`composeVersionString()`](https://github.com/JustArchiNET/ASF-ui/blob/efe00747b6ea2240364953754d85dedc0ea81807/src/utils/composeVersionString.js) function/file altogether, because it's still being [used elsewhere](https://github.com/JustArchiNET/ASF-ui/blob/efe00747b6ea2240364953754d85dedc0ea81807/src/components/NavigationBrand.vue#L57). As I'm not totally familiar with ASF-ui's codebase, I wasn't able to fully understand what kind of exception could be thrown [in this block of code](https://github.com/JustArchiNET/ASF-ui/blob/efe00747b6ea2240364953754d85dedc0ea81807/src/components/NavigationBrand.vue#L73-L86), that later will be [caught here](https://github.com/JustArchiNET/ASF-ui/blob/efe00747b6ea2240364953754d85dedc0ea81807/src/components/NavigationBrand.vue#L87-L90), passed to [`extractVersions()`](https://github.com/JustArchiNET/ASF-ui/blob/efe00747b6ea2240364953754d85dedc0ea81807/src/components/NavigationBrand.vue#L90), and finally passed to [`composeVersionString()` here](https://github.com/JustArchiNET/ASF-ui/blob/master/src/components/NavigationBrand.vue#L57). That's why I haven't removed it, so let me know if I should do something about that or just leave it like that.

This PR fixes #761. That's it, I guess. Thanks.

## Checklist

- [x] My pull request is not a duplicate
- [x] I added a descriptive title to this pull request
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Aareksio** [comment]
As for the backwards compatibility, you don't have to focus on this too much, as the only official distribution channel of the UI is bundled with ASF. Unless you are introducing breaking changes for features that are yet not implemented in ASF itself, it's fine.

As for the code, the `catch` is dirty workaround against Archi's preference to reduce error message to `oldVersion >= newVersion` when there's no new version of ASF available. In the catch, the logic filters and throws anything that's not looking like such response [here](https://github.com/JustArchiNET/ASF-ui/blob/efe00747b6ea2240364953754d85dedc0ea81807/src/components/NavigationBrand.vue#L88). Perhaps we should comment it better. I'm not sure what `result` is in `POST /asf/update`, you can consult swagger docs to check whether it changed to string or not.

**Comment by JustArchi** [comment]
Good thing you've reminded me, `/Api/ASF/Update` will also return version that is a string now, starting from V4.1.0.2.

**Comment by guixxx** [comment]
@Aareksio Thanks for the clarifications. Well, since Archi just mentioned that `/asf/update` will also return the version as a string now, I guess there's no point in having `composeVersionString()` anymore... Let me know if I'm missing something else.

**Comment by MrBurrBurr** [comment]
LGTM

**Comment by Botan626** [comment]
You couldn't wait another week for this PR to get one month old? Haste can be really counter-productive.

**Comment by butcha** [comment]
I am on 4.1.0.5, but I am still seeing the "undefined.undefined.undefined.undefined".

https://butcha.dk/i/orctu.png

**Comment by butcha** [comment]
I am on 4.1.0.5, but I still see the "undefined.undefined.undefined.undefined" in IPC.

orctu

**Comment by guixxx** [comment]
Try hitting Ctrl+Shift+F5

**Comment by butcha** [comment]
> Try hitting Ctrl+Shift+R

Yeah okay, I'm an idiot.. Haha. Sorry about that one :P

**Comment by guixxx** [comment]
No problem, I don't think the user is at fault in this case. I think ASF-ui should, somehow, inform the browser to discard the cached version once ASF-ui gets updated. Not entirely sure how, though.

**Pull request merged**
