### PR TITLE
Do not fetch release info for ASF versions that are newer than latest released

### LINKED ISSUE #1427: Don't fetch release info of installed version of ASF, if it's newer, than the latest released version
Opening Releases page in ASF-ui causes failing requests to GItHub.

image

Also, this will, probably, reduce time for this notification to appear, when user presses Update button, currently it takes more than 15 seconds.

image

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Fixes #1427

@Botan626 Feel free to verify if this works as expected.

### CODE REVIEW

**Comment by Botan626** [comment]
Did you fix both parts of #1427 issue, or just 1st part?

**Comment by MrBurrBurr** [comment]
I only fixed the main issue. The other part you described I can't reproduce.

**Comment by Botan626** [comment]
> I only fixed the main issue. The other part you described I can't reproduce.

1. Install ASF v5.1.1.2,
2. Press Update button in UI,
3. Count seconds until you see this notification: 
image

**Comment by Botan626** [comment]
The reason I'm mentioning this is because ASF shows its message immediately after Update button is pressed, while ASF-ui is checking for new version for 15+ seconds.

image

**Comment by Botan626** [comment]
Same amount of time ASF-ui needs to respond to `update` command.
image

**Pull request merged**
