### PR TITLE
Add navigation arrows to bot modals

### PR DESCRIPTION
**Pull request by MrBurrBurr**
## Description
This should come in handy when you want to switch between bots while in modal view.

## Screenshots
image

## Checklist

- [x] My pull request is not a duplicate
- [x] I added a descriptive title to this pull request
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by MrBurrBurr** [comment]
@Botan626 I know you like to test a lot, so feel free to test this new feature.

**Comment by Botan626** [comment]
I'm always happy to perform some ASF and ASF-ui tests. Happy Day!

How can I become Official ASF-ui Beta Tester?

What I noticed:

1. The width of Config panel can differ from bot to bot, so arrows will move left and right when switching between configs. Making Config window with a fix width will help I guess.

2. When fast switching via mouse clicking between panels, some elements become 'selected'.

chrome_FZYsmc8L8U
chrome_wrzqBbTMel
chrome_TsGovS7XlS

3. Holding down arrow keys freezes switching process.

**Comment by Botan626** [comment]
Up arrow could do the same as right arrow.

Down arrow could do the same as left arrow.

**Comment by MrBurrBurr** [comment]
Thank you for testing.

ps. If you have multiple whole page screenshots in your text, please make sure to link them instead of just pasting them. This will make it easier to read the text and assign the screenshots correctly. Example: 
> When fast switching via mouse clicking between panels, some elements become 'selected'. [Screenshot](https://user-images.githubusercontent.com/28785698/103240105-6a0f2e80-4960-11eb-8d11-ba7588ff0691.png)

**Comment by Botan626** [comment]
> If you have multiple whole page screenshots in your text, please make sure to link them instead of just pasting them. This will make it easier to read the text and assign the screenshots correctly.

Ok, I edited my comment.

**Pull request merged**
