### PR TITLE
Fix infinite loading loop

### LINKED ISSUE #1556: infinite loading loop
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] This is not a **[question](https://github.com/JustArchiNET/ASF-ui/issues/new?assignees=&labels=%E2%9D%93+Question&template=Question.yml)**
- [X] This is not **[ASF problem](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**
- [X] I cleared my cache and localStorage

### ASF version

Latest pre-release

### ASF-ui version

e35e350

### Bug description

Loading ASF-ui without any items present in the local storage results in the page loading infinitely (probably some sort of infinite recursion/loop).

### Expected behavior

The page loads and displays properly

### Actual behavior

The browser tab keeps loading without actually displaying stuff. Notice the loading animation in the top left corner

image

### Steps to reproduce

1. open current ASF-ui in an incognito tab
2. observe described behaviour

### Possible reason/solution

Maybe some infinite loop/recursion. I dont know exactly what could cause this. This is only an assumption.

### Can you help us with this bug report?

Somehow, I can test and offer feedback, but can't code

### Additional info

Thank you in advance for looking into this and fixing it!

Originally this was reported by @JustBuddy on our ASF discord server.

### PR DESCRIPTION
**Pull request by MrBurrBurr**
This should fix #1556, sorry for the delayed PR.

### CODE REVIEW

**Comment by Aareksio** [comment]
LGTM, someone needs to actually test it :)

**Review by JustArchi — COMMENTED** [review]
I have no clue what is happening here so I can't give any useful feedback :slightly_smiling_face:

**Review by Aareksio — APPROVED** [review]

**Comment by Abrynos** [comment]
> I have no clue what is happening here so I can't give any useful feedback

Neither have I. I can test it later tho

**Comment by Abrynos** [comment]
I just tested it. Should work fine.

**Review by Abrynos — APPROVED** [review]

**Pull request merged**
