### PR TITLE
Clear the whole terminal, including the input

### LINKED ISSUE #1151: CTRL + L shortcut does not clear the whole terminal
## Description
CTRL+L shortcut does not clear everything on the Commands page when executed.

## Steps to reproduce
1. Open Commands page in ASF-ui,
2. Type something in the terminal,
3. Press CTRL+L,
4. The stuff that you typed in stays.

## Expected behavior
Clear the whole terminal, or bring it to this state:
image

## Current behavior
Doesn't clear the input.

### PR DESCRIPTION
**Pull request by MrBurrBurr**
## Description
Fixes #1151 

## Checklist

- [x] My pull request is not a duplicate
- [x] I added a descriptive title to this pull request
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Abrynos** [comment]
As per comment in the ticket, I believe the current behaviour is correct.

**Comment by MrBurrBurr** [comment]
We will see where the discussion in #1151 leads to and then either merge or close this PR.

**Comment by Botan626** [comment]
I tested your commit and it doesn't work.
https://i.imgur.com/j1H9tCe.gif

**Comment by MrBurrBurr** [comment]
Should work now. Feel free to confirm.

**Comment by Botan626** [comment]
> Should work now. Feel free to confirm.

Still doesn't work.
https://i.imgur.com/iBlb5Ow.gif

**Comment by MrBurrBurr** [comment]
All good things come in threes. Now it works. I will bet.

**Comment by Botan626** [comment]
Now it does the job.

**Comment by MrBurrBurr** [comment]
This PR was closed due to #1158 getting merged instead.

**Pull request closed without merging**
