### PR TITLE
Optimize for small resolution

### LINKED ISSUE #352: Make ASF-ui to work properly with small width
For the first two cases ASF-ui could show only 1 bot card in a row:

https://i.imgur.com/MQtqAqg.png

https://i.imgur.com/5TZ9AKb.png

The cursor is not visible in Commands window:

https://i.imgur.com/SVTdrxb.png

Same for other windows.

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Closes #352

### CODE REVIEW

**Comment by Aareksio** [comment]
DOn't you dare merge this

**Comment by MrBurrBurr** [comment]
Why not?

**Comment by Aareksio** [comment]
Because this breaks the intended, proper behavior?

Current:
screen shot 2019-02-04 at 15 21 08
screen shot 2019-02-04 at 15 19 43

After change:
screen shot 2019-02-04 at 15 20 58

**Comment by Aareksio** [comment]
screen shot 2019-02-04 at 15 20 58
screen shot 2019-02-04 at 15 29 16
screen shot 2019-02-04 at 15 29 43
screen shot 2019-02-04 at 15 29 53

I do see _a few_ other issues, if you solve them, then I'm fine with the change, but only after.

**Pull request merged**
