### PR TITLE
Sort commands list that will be shown to user

### PR DESCRIPTION
**Pull request by MrBurrBurr**
## Description
When the user enters the 'commands' command he will get a list of all available commands. This list consists of asf-commands and asf-ui-commands. Instead of just appending the asf-ui-commands to the asf-commands we now sort them so the user has an easier time finding the command he is searching for.

## Checklist
- [x] My pull request is not a duplicate
- [x] I added a descriptive title to this pull request
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by Abrynos** [comment]
May I ask what the reason behind this sorting is? I can't really see an advantage of them being sorted alphabetically (I can't really see an advantage in the current version either for that matter)

**Comment by MrBurrBurr** [comment]
It's just nicer to look at and I think user would expect it to be alphabetically sorted.

image

**Comment by JustArchi** [comment]
It'd be even better if ASF-ui displayed its own commands and ASF commands as two independent rows.

**Comment by JustArchi** [comment]
That's just my own opinion of course, I just believe bundling them together (sorted or not) is counter-intuitive, there should be distinction between those two and then they should be sorted in their own rows.

**Comment by MrBurrBurr** [comment]
I was also thinking about that but its just 3 commands: `clear, help and commands`

Now I am wondering if `commands` and `help` would be something that ASF could provide in the future?

**Comment by Abrynos** [comment]
I'm definitely with Archi when he prefers them separately. On the "I think user would expect it to be alphabetically sorted" I am not with you tho. I am used to the `man {cmd}` command on linux to read the manual of some application. An example of a (in my opinion) good manual would be grep (`man grep`). There the options are grouped logically (and only in those groups are they sorted alphabetically). I understand, that grouping them is much harder here, but I also don't think, that ordering all of them in one big list is that much of an advantage over the previous versions.

You might also consider ordering them once and holding that instead of ordering them every time a user requests them ;)

**Comment by MrBurrBurr** [comment]
Feel free to also review my changes @Abrynos. I just [can't select you](https://user-images.githubusercontent.com/31552675/97040459-3c77c480-156e-11eb-8bdd-e807a274e59c.png) as a reviewer.

**Review by JustArchi — APPROVED** [review]
LGTM

**Review by Abrynos — APPROVED** [review]
LGTM

**Pull request merged**
