### PR TITLE
Don't send additional requests if user is unauthorized

### LINKED ISSUE #1483: Do not send request on each page reload on login page
Currently it does, which gives rate limited status.

<details>
  <summary>Screenshot</summary>
  
image

</details> 

Reference: https://discord.com/channels/267292556709068800/859553121856258058/868164666520637522

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Closes #1483 

@Botan626 Feel free to give it a try.

### CODE REVIEW

**Comment by MrBurrBurr** [comment]
@Botan626 After some discussion on discord I will rework this a bit. So please wait until I implemented those changes.

**Comment by MrBurrBurr** [comment]
@Botan626 Now it should be ready.

**Comment by Botan626** [comment]
I already reported it on Discoed.

image

**Comment by Botan626** [comment]
Also, if I set `IPCPassword`, open UI and see login page, but then decide to close UI and remove `IPCPassword` from ASF.json, UI will still show me login page, when I open it.

First press on Continue button will dismiss login page in this case.

**Comment by MrBurrBurr** [comment]
> Also, if I set `IPCPassword`, open UI and see login page, but then decide to close UI and remove `IPCPassword` from ASF.json, UI will still show me login page, when I open it.
> 
> First press on Continue button will dismiss login page in this case.

This is as intended.

> I already reported it on Discord.

Please report it here again with how to reproduce. With just a screenshot of a error message I can't really get much info out of it.
Also note that this error is probably out of scope for this PR.

**Comment by Botan626** [comment]
> This is as intended.

Well, if you say, that such behaviour should stay, then good luck and farewell, skurr, continuing developing ASF-ui, without me.
Because I disagree with that, it's like I'm turning my passcode off on my phone, lock it, unlock it and still see screen to enter passcode.

But getting around it will require resolving [this issue](https://github.com/JustArchiNET/ASF-ui/issues/1480) too, I guess.

> Also note that this error is probably out of scope for this PR.

Probably, but all it takes to see it is enabling `IPCPassword`, opening UI with default IPC address and opening console. Basic steps. You didn't do it?

**Comment by Aareksio** [comment]
The console error is caused by navigation being aborted in navigation guard (eg. `beforeEnter`). If we call `next(newLocation)` it makes `$router.push(intendedLocation)` throw an error. This is somewhat _recent_ update to `vue-router`.

From the error message it seems Botan landed on `/setup` page anyway. It may be good idea to check in `beforeRoute` if current `to` is different from the route we plan to enforce. Another solution would be to mount `.catch()` on `$router.push` which caused the navigation.

**Comment by Botan626** [comment]
@Aareksio What do you think about an [issue](https://github.com/JustArchiNET/ASF-ui/issues/1480) I linked above?

**Pull request merged**
