### PR TITLE
Disable terminal input while waiting for response

### LINKED ISSUE #108: Improve terminal response
If you have a lot of bots and decide to use a command which will need some time to process (`!addlicense asf` for example) it would be nice to see that the terminal is still waiting for a response or that asf is still processing your command. Maybe even lock the input until we got our response.

### PR DESCRIPTION
**Pull request by Aareksio**
@MrBurrBurr Could you please see whether it's the desired behavior?

Closes #108

### CODE REVIEW

**Comment by MrBurrBurr** [comment]
I will check later today, thank you.

**Comment by MrBurrBurr** [comment]
Maybe we could further improve it by displaying some kind of loading animation.

Currently its just disabled and this could confuse the user into thinking that the terminal is not working.

**Comment by Aareksio** [comment]
Depends on the program you execute, usually (unless the program attaches to input) they just let you type. CMD and PS do not display user input untill the program finished execution (but still preserve it). Bash both displays it as you type, then once again in input line, attaching screen for better visualization.

bash

If we were to mimic either, we could make input transparent (instead of disabled) before the answer arrives.

I don't think we should change anything though.

**Comment by JustArchi** [comment]
If you want to mimic commands sent via Steam chat then there should be no any sort of disable, user should be able to send several commands at once, and they should arrive as API calls finish, even in reverse order if first command takes the most time.

Although it's up to you if you want to mimic this behaviour or not. To me this makes sense, I don't see a reason why I shouldn't be able to do `addlicense asf 12345` and in the meantime while waiting do `version` and get the output to that one. If you at all cost want to tell user that command is executing, you could add a small hourglass to the left/right of the command, or animated `...` at the end that would indicate that command is in progress.

I definitely don't see a reason for limiting terminal to one command at a time.

**Comment by MrBurrBurr** [comment]
I agree that it actually doesn't make sense to disable input. We should not do that. I am sorry for not thinking about it and suggesting it.

**But** I would really like to see some kind of animation that the command I sent is still being processed. I like both ideas suggested by Archi so it would be up to you (Mole) which one we should implement.

**Comment by Aareksio** [comment]
Like this?
Demo GIF

**Comment by MrBurrBurr** [comment]
I like it very much.

**Comment by Aareksio** [comment]
Or a spinner...?
Spinner demo GIF

**Comment by MrBurrBurr** [comment]
I think the first one is better because user can see which command is being processed.

**Comment by Aareksio** [comment]
It's always the command above, so I'm not sure that's needed.
Also, this clutters the view and makes screen flash on commands that respond fast.

**Comment by MrBurrBurr** [comment]
Considering what you said I think the second one is better.

**Pull request closed without merging**
