### PR TITLE
Add Ctrl+U shortcut

### PR DESCRIPTION
**Pull request by nuckle**
## Description

Closes this issue - https://github.com/JustArchiNET/ASF-ui/issues/1689

## Screenshots

<details>
  <summary>Before pressing Ctrl+U</summary>
  Before pressing Ctrl+U
</details>

<details>
  <summary>After pressing Ctrl+U</summary>
  After pressing Ctrl+U
</details>

## Additional information

This shortcut needs to be listed here - https://github.com/JustArchiNET/ASF-ui/wiki/Features#shortcuts

## Checklist

- [x] My pull request is not a duplicate
- [x] I added a descriptive title to this pull request
- [x] I added a concise description or a self-explanatory screenshot to this pull request
- [x] My code follows the code style of this project
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Review by Aareksio — APPROVED** [review]
If `nextTick` works here, I'd use it instead of `setTimeout`

**Comment by nuckle** [comment]
Like so?

```js
      jumpToStart() {
        const el = this.$refs['terminal-input'];
        if (el.setSelectionRange) el.setSelectionRange(0, 0);
      },

      deleteBeforeCursorAndJumpToStart() {
        this.removeBeforeCursor();
        this.$nextTick(() => {
          this.jumpToStart();
        })
      },
```

**Comment by Aareksio** [comment]
I'd just replace setTimeout with next tick:
```ts
if (el.setSelectionRange) {
  this.$nextTick(() => el.setSelectionRange(0, 0));
}
```

**Comment by nuckle** [comment]
I'm not sure about this too, but it's required in this case to use `setTimeout` or `nextTick`. I decided to use `setTimeout`, because there's a similar function `moveCursorToEnd` that uses this. But I agree that `nextTrick` is a better choice 

```js
moveCursorToEnd() {
  const el = this.$refs['terminal-input'];
  const len = this.command.length;

  if (el.setSelectionRange) setTimeout(() => el.setSelectionRange(len, len), 0);
}
```

**Comment by Aareksio** [comment]
Ah right, you followed the pattern. This is good. @MrBurrBurr merge? Apart from fulfilling Botan's request, this looks solid and harmless.

**Comment by MrBurrBurr** [comment]
I will take a look and see why we are using `setTimeout` and if we need it or if it could be replaced with `nextTick`.

Other than that, thank you for your contribution!

**Review by MrBurrBurr — APPROVED** [review]

**Pull request merged**
