### PR TITLE
Make it clearer that user filtered visible bots

### LINKED ISSUE #1564: Make it clearer that user filtered visible bots
### Checklist

- [X] I read and understood ASF-ui's **[Contributing Guidelines](https://github.com/JustArchiNET/ASF-ui/blob/main/.github/CONTRIBUTING.md)**
- [X] I also read **[FAQ](https://github.com/JustArchiNET/ASF-ui/wiki/FAQ)**
- [X] My idea doesn't duplicate existing ASF-ui functionality described on the **[wiki](https://github.com/JustArchiNET/ASF-ui/wiki)**
- [X] I believe that my idea falls into ASF-ui's scope and should be offered as part of ASF-ui built-in functionality
- [X] This is not **[ASF suggestion](https://github.com/JustArchiNET/ArchiSteamFarm/issues/new/choose)**

### Enhancement purpose

obraz

### Solution

I imagine we should grey-out the unselected options instead, maybe leaving the current green highlight for additional visibility, but that alone is not sufficient.

### Why currently available solutions are not sufficient?

It's not the first time somebody is confused what happened.

### Can you help us with this enhancement idea?

Somehow, I can test and offer feedback, but can't code

### Additional info

_No response_

### PR DESCRIPTION
**Pull request by MrBurrBurr**
Closes #1564

@JustArchi @Abrynos 
Feel free to let me know what you think.

### CODE REVIEW

**Comment by Aareksio** [comment]
Could you please attach a screenshot with this mostly visual PR?

**Comment by MrBurrBurr** [comment]
@Aareksio 
image

**Comment by Aareksio** [comment]
I think a smaller banner would do better job here. We're handling edge case, covering such a big portion of the screen is counter productive. A single line `Showing <strong>0/xxx</strong> bots, <a>reset filters</a>` might be more fitting.

Apart from the visuals, it gets the job done!

**Comment by MrBurrBurr** [comment]
@Aareksio 
image
image

**Review by JustArchi — APPROVED** [review]
I don't know a thing about this, but it looks good :sunglasses:

**Comment by Abrynos** [comment]
LGTM. Sorry for the late answer.

**Pull request merged**
